### ISSUE TITLE
090-2930 Error code

### ISSUE THREAD

**Issue by HOAsAreFullOfComunists** [MettleSphee/3DS_EpisodeGenerator_AnimeTemplate#1]
I used your generator and the episodes have succesfully showed up. Well, kind of. The thumbnails didn't appear and the videos didn't play (instead, I got the 090-2930 Error). I hope I'm not bothering you. I uploaded the catalouge in case you want to see.
[catalog.json](https://github.com/user-attachments/files/18247030/catalog.json)

**Comment by MettleSphee** [comment]
The JSON part (starting after "= ", ending before the line "end") is fine, but your file also contains some other things, and I presume the file goes all into "debugcatalog.lua" and not as a separate json. Make sure all links are valid and working (for the videos themselves)

For the archive.org links, I have tested your links, and they will NOT work as they are. You have to get the DIRECT link to the files. Here's how I did it:
Download the file from archive.org (or just queue it in a downloader if you have it);
Look in the downloads list in your browser (or in the queue of your downloader) and get the link.

Here's one of your videos examples: 
You had this link: https://archive.org/download/bitte-esst-keine-besen/Ein%20Langes%20Rohr.moflex
You should have had THIS link: https://ia600605.us.archive.org/32/items/bitte-esst-keine-besen/Ein%20Langes%20Rohr.moflex

Notice how the link starts with ia<numbers>.us.archive.org, and has your item directly.

Just replace the links and you'll be fine.

**Comment by HOAsAreFullOfComunists** [comment]
Thank you! You're a life saver!
